services:
  hackathon-db:
    image: 'bitnami/postgresql:15'
    container_name: hackathon-db
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=hackathondb
    ports:
      - 5434:5432
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - app-network

volumes:
  postgresql_data:
    driver: local

networks:
  app-network:
