apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hackathon-postgres-db
  labels:
    app: hackathon-postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-postgres-db
  serviceName: "hackathon-postgres-db" # Matches the headless service name
  template:
    metadata:
      labels:
        app: hackathon-postgres-db
    spec:
      automountServiceAccountToken: false
      containers:
        - name: hackathon-postgres-db
          image: postgres:15 # Use the official PostgreSQL image
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: docker # Set the PostgreSQL username
            - name: POSTGRES_PASSWORD
              value: docker # Set the PostgreSQL password
            - name: POSTGRES_DB
              value: hackathondb # Set the default database name
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "500Mi"
            limits:
              memory: "2Gi"
              ephemeral-storage: "4Gi"
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: hackathon-postgres-db
  labels:
    app: hackathon-postgres-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None # Headless service required for StatefulSet
  selector:
    app: hackathon-postgres-db
---