apiVersion: v1
kind: Service
metadata:
  name: hackathon-nest
  labels:
    app: hackathon-nest
spec:
  selector:
    app: hackathon-nest
  ports:
    - name: http 
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort